# Generated by Django 5.0.1 on 2024-01-31 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourses', '0002_alter_product_colors_alter_product_gallery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsize',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
