# Generated by Django 5.0.1 on 2024-02-04 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourses', '0004_alter_productsize_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcolor',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='productsize',
            options={'ordering': ['size_group', 'order']},
        ),
        migrations.AddField(
            model_name='productcolor',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='productcolor',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='color',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
