# Generated by Django 5.0.1 on 2024-02-05 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourses', '0005_alter_productcolor_options_alter_productsize_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='header_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
