# Generated by Django 5.0.1 on 2024-02-08 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourses', '0008_alter_product_header_image_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcolor',
            name='color',
            field=models.CharField(default='#000000', max_length=100, unique=True),
        ),
    ]
