# Generated by Django 5.0.1 on 2024-02-08 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourses', '0009_alter_productcolor_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcolor',
            name='color',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
